services:
  app:
    build:
      context: .
      args:
        NODE_VERSION: 22
    image: ptamp-app
    container_name: ptamp-app
    restart: unless-stopped
    extra_hosts:
      - "db-host:host-gateway"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgresql://vpsdepati:Vpsdepati.123!@db-host:5432/ptamp?schema=public"
    ports:
      - "3000:3000"
    # Using standalone output, so we don't need to mount volumes for code or build artifacts in production
    # command: node server.js # This is the default CMD in the Dockerfile
